name: Manually Publish Docker Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Enter the tag name to publish (e.g., v1.0.0)"
        required: true  # User must enter a tag

jobs:
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t myrepo/myapp:${{ github.event.inputs.tag_name }} .
          docker push myrepo/myapp:${{ github.event.inputs.tag_name }}
