name: Docker Build Reusable

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate Tag Exists
        run: |
          git fetch --tags
          git tag | grep -qx "${{ inputs.tag }}" || \
            (echo "❌ Tag '${{ inputs.tag }}' does not exist" && exit 1)

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build --prod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: viveksinghsahu/visi-webapps:${{ inputs.tag }}
          platforms: linux/amd64,linux/arm64
