name: Angular Feature Branch Testing

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  test-angular:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Run Linting
        run: npm run lint
